[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "tdse"
version = "0.0.3"
dependencies = ["numpy","scipy","pytest","pytest-cov","matplotlib","findiff"]
